Raise required compiler to rust 1.60
Required by reqwest 0.12.

    error: failed to select a version for the requirement `reqwest = "^0.12"`
    candidate versions found which didn't match: 0.11.23, 0.11.22, 0.11.21, ...
    location searched: crates.io index
    required by package `unsafe-libyaml-test-suite v0.0.0`