Raise minimum tested compiler to 1.63
Required by socket2.

    error: package `socket2 v0.5.3` cannot be built because it requires
    rustc 1.63 or newer, while the currently active rustc version is 1.62.0